# Generated by Django 3.2.11 on 2023-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('LTR', 'Liter'), ('GM', 'Gram'), ('Pc', 'Pc')], default='KG', max_length=7),
        ),
    ]
