# Generated by Django 3.2.11 on 2023-01-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
    ]
