# Generated by Django 4.2 on 2024-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('LTR', 'Liter'), ('gm', 'Gram'), ('Pc', 'Pc')], default='KG', max_length=7),
        ),
    ]
