# Generated by Django 5.2.3 on 2025-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_options_product_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('Lt', 'Liter'), ('Gm', 'Gram'), ('Pc', 'Pc')], default='Kg', max_length=7),
        ),
    ]
