# Generated by Django 5.2.3 on 2025-07-05 22:26

from django.db import migrations, models
from django.db.models import Count

def update_product_count(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')

    # Update product_count for each category
    categories = Category.objects.all()
    for category in categories:
        product_count = Product.objects.filter(category=category).count()
        category.product_count = product_count
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(update_product_count, reverse_code=migrations.RunPython.noop),
    ]
