# Generated by Django 5.2.12 on 2026-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_extract_brands_and_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
