# Generated by Django 5.2.12 on 2026-08-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_add_category_brand_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand_filter',
        ),
        migrations.AddField(
            model_name='category',
            name='shows_speciality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_speciality',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
