"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from django.conf import settings
from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv
env = load_dotenv(find_dotenv(), override=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-jzf&g27u%23e7fd+=yf+=)3kf5)-8&tfo7d)6mxkn^pz4_1iz)"
SECRET_KEY = os.getenv("SECRET_KEY")
# print(SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG_VAL = os.getenv("DEBUG")
DEBUG = DEBUG_VAL == "True"
# print(type(DEBUG))

ALLOWED_HOSTS = [
    "www.19onlineshop.com",
    "localhost",
    "127.0.0.1",
    ".up.railway.app",
    "19onlineShop.com",
    "192.168.0.101",
]
CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
]
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",                     # required by allauth
    "rest_framework",
    "store.apps.StoreConfig",
    "corsheaders",
    "cloudinary",
    "cloudinary_storage",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

SITE_ID = 1

# --- allauth ----------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",      # admin login
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Skip the local-account flows entirely — shoppers only sign in with Google.
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True          # don't show an intermediate signup form
SOCIALACCOUNT_LOGIN_ON_GET = True         # skip the confirm-login page on a GET
LOGIN_REDIRECT_URL = "/checkout"          # bounce back to checkout after Google OAuth
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online", "prompt": "select_account"},
    },
}
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    # No auth on the storefront. Without this, DRF's default
    # SessionAuthentication would CSRF-check POSTs whenever a session cookie
    # is present (e.g. after an admin login in the same browser), causing
    # 403 Forbidden on /store/order/.
    "DEFAULT_AUTHENTICATION_CLASSES": [],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

CSRF_TRUSTED_ORIGINS = ['https://19onlineshop.com', 'https://www.19onlineshop.com', 'http://localhost:3000', 'https://*.up.railway.app']

# Railway's edge terminates SSL and forwards as HTTP. Without this Django
# builds absolute URIs with http:// (including the Google OAuth redirect_uri),
# which Google then rejects as a mismatch.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases



if DEBUG:
    print("DEBUG MODE")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME"),
            'USER': 'postgres',
            'PASSWORD': os.getenv("DB_PASSWORD"),
            'HOST': os.getenv("DB_HOST"),
            'PORT': os.getenv("DB_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# time zone of india
TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# if True:
#     # Development: Serve static files directly from frontend build directory
#     STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
#     STATICFILES_DIRS = [
#         os.path.join(BASE_DIR, "frontend/static/frontend"),
#     ]
# else:
    # Production: Use compressed manifest storage
STORAGES = {
    # Always Cloudinary for media — so a local dev DB seeded with a copy of
    # prod sees the same image URLs as prod, and locally-uploaded images
    # land in the same place too (no /media/ 404s from missing local files).
    # Requires CLOUDINARY_URL in .env.
    "default": {"BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        )
    },
}

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "static/"

# Serve the Vite SPA build (web/dist/) at the site root via Whitenoise.
# `npm run build` in web/ produces web/dist/; collectstatic pulls it into
# STATIC_ROOT. The SPA's index.html is served at /, and the catch-all view
# in core/urls.py serves it for any unmatched client-side route.
STATICFILES_DIRS = [os.path.join(BASE_DIR, "web", "dist")]
WHITENOISE_ROOT = os.path.join(BASE_DIR, "staticfiles")
WHITENOISE_INDEX_FILE = True

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"

# Cloudinary — non-DEBUG environments store uploaded media on Cloudinary CDN.
# DEBUG=True keeps FileSystemStorage so local dev doesn't need Cloudinary creds.
CLOUDINARY_STORAGE = {
    "CLOUDINARY_URL": os.getenv("CLOUDINARY_URL"),
}


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
